version: "3.9"
services:
  backend1:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
  backend2:
    build: ./backend
    ports:
      - "5002:5000"
    env_file:
      - ./backend/.env
  backend3:
    build: ./backend
    ports:
      - "5003:5000"
    env_file:
      - ./backend/.env
